import type { Metadata } from 'next';
import { Poppins } from 'next/font/google';
import './globals.css';

const poppins = Poppins({
  weight: ['400', '500', '600', '700'],
  subsets: ['latin'],
});

export const metadata: Metadata = {
  title: 'Micro SaaS',
  description: 'Generated by create next app',
  openGraph: {
    title: 'Micro SaaS',
    description: 'Generated by create next app',
    url: 'https://micro-saas-gules.vercel.app/',
    siteName: 'Micro SaaS',
    images: [
      {
        url: 'https://micro-saas-gules.vercel.app/opengraph-image-1ncyxl.png?d1007eab37e99ee4',
      },
    ],
    locale: 'pt_BR',
    type: 'website',
  },
  twitter: {
    card: 'summary_large_image',
    title: 'Micro SaaS',
    description: 'Generated by create next app',
    images: [
      'https://micro-saas-gules.vercel.app/opengraph-image-1ncyxl.png?d1007eab37e99ee4',
    ],
  },
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="pt-BR">
      <body className={`${poppins.className} bg-gray-100 antialiased`}>
        {children}
      </body>
    </html>
  );
}
